# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3db97fe826e75aa81f450d4dce327fb7fef2f62850b16185c6a49c86e3d0f879beaa2fec577e4799d5ce746f2e166481fd9c78bf6ec4d8895ab321ce3b64fa59

test:
  secret_key_base: 9e7e591827c635c3baa99360cdc60f202ff99c1b5d0cac02854f8c49786cc5b8e17357597f421568e5b6ee3c62c634fa95a348870cb79645df9f515b2a705a00

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
